### ISSUE TITLE
IPy dependency appears to be broken

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#1003]
```
~/P/r/otter: pip install -r cafe_requirements.txt; and python -c "import IPy"                                                                                                                       13:30:39
You are using pip version 6.0.6, however version 6.0.7 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting opencafe from git+https://github.com/stackforge/opencafe.git@b971070b28d07c0b19f8809e18950f2d6cf0e466#egg=opencafe (from -r cafe_requirements.txt (line 1))
  Cloning https://github.com/stackforge/opencafe.git (to b971070b28d07c0b19f8809e18950f2d6cf0e466) to /var/folders/2w/kffqc_pj6m38rgrxlhk8z6nr0000gn/T/pip-build-5wPruU/opencafe
  Could not find a tag or branch 'b971070b28d07c0b19f8809e18950f2d6cf0e466', assuming commit.
Requirement already satisfied (use --upgrade to upgrade): cloudcafe from git+https://github.com/stackforge/cloudcafe.git@4dc2227b4b0140158ceab286dfa127384886f5b7#egg=cloudcafe in /Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages (from -r cafe_requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): IPy==0.82a in /Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages (from -r cafe_requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): decorator in /Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages (from opencafe->-r cafe_requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): paramiko in /Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages (from opencafe->-r cafe_requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): requests==1.2.0 in /Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages (from opencafe->-r cafe_requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): pymongo==2.5 in /Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages (from opencafe->-r cafe_requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): argparse==1.2.1 in /Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages (from opencafe->-r cafe_requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): unittest2==0.5.1 in /Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages (from opencafe->-r cafe_requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): httpretty in /Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages (from cloudcafe->-r cafe_requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): mock in /Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages (from cloudcafe->-r cafe_requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): pycrypto!=2.4,>=2.1 in /Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages (from paramiko->opencafe->-r cafe_requirements.txt (line 1))
Installing collected packages: opencafe
  Running setup.py install for opencafe
    Installing cafe-runner script to /Users/lvh/.pyenv/versions/otter/bin
    		     ( (
    		        ) )
    		     .........
    		     |       |___
    		     |       |_  |
    		     |  :-)  |_| |
    		     |       |___|
    		     |_______|
    		 === CAFE Core ===
    ========================================================
    CAFE Core installed with the options:
    Config File: /Users/lvh/.cloudcafe/configs/engine.config
    log_directory=/Users/lvh/.cloudcafe/logs
    data_directory=/Users/lvh/.cloudcafe/data
    temp_directory=/Users/lvh/.cloudcafe/temp
    use_verbose_logging=False
    ========================================================
Successfully installed opencafe
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named IPy
~/P/r/otter: pip uninstall IPy; and pip install IPy; and python -c "import IPy"                                                                                                                     13:30:57
You are using pip version 6.0.6, however version 6.0.7 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Can't uninstall 'IPy'. No files were found to uninstall.
You are using pip version 6.0.6, however version 6.0.7 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): IPy in /Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named IPy
~/P/r/otter: pip install IPy; and python -c "import IPy"                                                                                                                                            13:31:29
You are using pip version 6.0.6, however version 6.0.7 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): IPy in /Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named IPy
~/P/r/otter: pip install --upgrade IPy                                                                                                                                                              13:31:42
You are using pip version 6.0.6, however version 6.0.7 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting IPy from https://pypi.python.org/packages/source/I/IPy/IPy-0.82.tar.gz#md5=0625e884df8bde533b54a88c85cf5029
  Using cached IPy-0.82.tar.gz
Installing collected packages: IPy
  Found existing installation: IPy 0.82a0
    Can't uninstall 'IPy'. No files were found to uninstall.
  Running setup.py install for IPy
Successfully installed IPy-0.81
~/P/r/otter: python -c "import IPy"                                                                                                                                                                 13:31:56
~/P/r/otter:   
```

**Comment by lvh** [comment]
Can't reproduce anymore :/
