### ISSUE TITLE
Active server links JSON not written to DB

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1119]
Listing groups for a convergence tenant results in the following traceback:

```
Traceback (most recent call last):
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
    self._runCal
lbacks()
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 578, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/otter/.ve/local
/lib/python2.7/site-packages/twisted/internet/defer.py", line 383, in callback
    self._startRunCallbacks(result)
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 491,
 in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 578, in _runCallbacks
    current.resu
lt = callback(current.result, *args, **kw)
  File "/opt/otter/otter/rest/groups.py", line 181, in format_list
    } for state in group_states]
  File "/opt/otter/otter/rest/groups.py", line 74, in format_sta
te_dict
    } for key, server_blob in state.active.iteritems()
exceptions.KeyError: 'links'
```

Because in the DB, an example of the data stored in active servers looks like:

`{"test-server2137886081-id-2137886081": {"id": "test-server2137886081-id-2137886081"}, "test-server2913956880-id-2913956880": {"id": "test-server2913956880-id-2913956880"}}`

The worker stores a lot more info, but the only things autoscale presents to the user are the `id` and the `links`, so just making sure the links are available will probably solve this bug.

Can be solved probably as part of #1106.

This should make a bunch of functional tests pass.

**Comment by cyli** [comment]
For reference, a DB entry for active servers produced by the worker look like:

`{"test-server8057297169-id-8057297169": {"id": "test-server8057297169-id-8057297169", "links": [{"href": "http://localhost:8900/mimicking/NovaApi-3bab1e/ORD/v2/111111/servers/test-server8057297169-id-8057297169", "rel": "self"}, {"href": "http://localhost:8900/mimicking/NovaApi-3bab1e/ORD/111111/servers/test-server8057297169-id-8057297169", "rel": "bookmark"}], "name": "test_sg_bhv_srv424679-as5fde94d9", "lb_info": [], "created": "2015-02-20T20:40:14.790059Z"}, "test-server5196953637-id-5196953637": {"name": "test_sg_bhv_srv424679-as9148a19f", "links": [{"href": "http://localhost:8900/mimicking/NovaApi-3bab1e/ORD/v2/111111/servers/test-server5196953637-id-5196953637", "rel": "self"}, {"href": "http://localhost:8900/mimicking/NovaApi-3bab1e/ORD/111111/servers/test-server5196953637-id-5196953637", "rel": "bookmark"}], "id": "test-server5196953637-id-5196953637", "lb_info": [], "created": "2015-02-20T20:40:14.846512Z"}, "_ver": 1, "test-server5785648061-id-5785648061": {"lb_info": [], "created": "2015-02-20T20:40:14.856580Z", "id": "test-server5785648061-id-5785648061", "links": [{"href": "http://localhost:8900/mimicking/NovaApi-3bab1e/ORD/v2/111111/servers/test-server5785648061-id-5785648061", "rel": "self"}, {"href": "http://localhost:8900/mimicking/NovaApi-3bab1e/ORD/111111/servers/test-server5785648061-id-5785648061", "rel": "bookmark"}], "name": "test_sg_bhv_srv424679-as261fed64"}}`
