### ISSUE TITLE
Trim our CF messages to be <= 255 chars long or up our CF schema so messages can be > 255 chars

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1583]
So we can't log messages that include things like the server config a server was created with - we probably can't have many details in the messages.

If we want to include details like that, we need to put it elsewhere maybe (which involves a schema change).

Our Cloudfeeds observer/our cf logging niceties should probably also check that we're not attempting to log messages over 255 characters in length.

**Comment by cyli** [comment]
This was the error we got back:

Traceback (most recent call last):
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/effect/_continuation.py", line 25, in bounce
    trampoline(func, *args, **kwargs)
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/effect/_continuation.py", line 56, in trampoline
    f(bouncer, *args, **kwargs)
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/effect/_base.py", line 142, in _run_callbacks
    bouncer.bounce(_run_callbacks, chain, result)
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/effect/_base.py", line 85, in guard
    return (True, sys.exc_info())
--- <exception caught here> ---
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/effect/_base.py", line 83, in guard
    return (False, f(*args, **kwargs))
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/effect/retry.py", line 25, in maybe_retry
    six.reraise(*error)
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/effect/_base.py", line 83, in guard
    return (False, f(*args, **kwargs))
  File "/opt/otter/otter/util/pure_http.py", line 99, in check_response
    raise APIError(response.code, content, response.headers)
otter.util.http.APIError: API Error code=400, body='{\n    "error" : {\n        "@type" : "http://abdera.apache.org",\n        "code" : 400,\n        "message" : "The following error was encountered after the JSON body was converted to XML: Bad Content: Validating product/@message: Value "Creating 1 with config {\'serve..." contravenes the maxLength facet "255" of the type string"\n    }\n}', headers=Headers({'date': ['Tue, 14 Jul 2015 23:12:49 GMT'], 'content-encoding': [''], 'via': ['1.1 Repose (Repose/7.0.1.1)'], 'content-type': ['application/json'], 'server': ['Jetty(9.2.z-SNAPSHOT)']})

**Comment by cyli** [comment]
Just mentioning it here for tracking - the CF team replied and said we can set `maxLength` in the CF schema in `string` attributes, so the message can be > 255 chars.

example:  https://github.com/rackerlabs/standard-usage-schemas/blob/master/sample_pro
duct_schemas/emailapps_msservice.xml#L21

So this might be what we want to do

**Comment by cyli** [comment]
Update from the CF team - there is no current limit on the size of the event, but they are considering making it 2M.

**Comment by cyli** [comment]
This is done - I'll open a new issue for increasing the limit, if necessary.
