### ISSUE TITLE
CF observer logs a message twice to CF

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1584]
Created a group with minentities 1, and an invalid load balancer.

Logging to https://gist.github.com/cyli/1f6b1f832c2e3f4d79f6.

Seeing 4 CF messages with the same message ID.

This is likely related to #1580

**Comment by cyli** [comment]
Ok, this was because I was using a request bin that was returning the wrong status code (202 instead of 201), and so it was repeatedly retrying.  There were more than 4 events, I just killed it too early.  

This is also a problem in production because we are getting a 400 back for some messages that are too long, and we are just retrying them again.

We should probably stop retrying on 4XX and just log that as an error, since we already re-auth on 401 and 403.

**Comment by cyli** [comment]
Hmm... I'm not seeing the duplicate ID error again when testing against production - trying again.

**Comment by cyli** [comment]
Ok, against prod: I only do not see a duplicate ID when I do not include the invalid load balancer - in that case, I see only that otter tried to post a too-long message to cloud feeds 5 times, and 5 times it failed with a 400.

Finally, ends up with the error given in #1583.

If I include an invalid load balancer in the autoscale launch config args, then I see the 400's from the too-long message, and then this:

```
Traceback (most recent call last):
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/effect/_continuation.py", line 25, in bounce
    trampoline(func, *args, **kwargs)
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/effect/_continuation.py", line 56, in trampoline
    f(bouncer, *args, **kwargs)
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/effect/_base.py", line 142, in _run_callbacks
    bouncer.bounce(_run_callbacks, chain, result)
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/effect/_base.py", line 85, in guard
    return (True, sys.exc_info())
--- <exception caught here> ---
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/effect/_base.py", line 83, in guard
    return (False, f(*args, **kwargs))
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/effect/retry.py", line 25, in maybe_retry
    six.reraise(*error)
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/effect/_base.py", line 83, in guard
    return (False, f(*args, **kwargs))
  File "/opt/otter/otter/util/pure_http.py", line 99, in check_response
    raise APIError(response.code, content, response.headers)
otter.util.http.APIError: API Error code=409, body='<?xml version="1.0" encoding="UTF-8"?><error xmlns="http://abdera.apache.org"><code>409</code><message>Unable to persist entry. Reason: entryId (urn:uuid:0fcc3d6c-62a3-4bdb-9aae-e3168c5e0a7e) not unique.</message></error>', headers=Headers({'via': ['1.1 Repose (Repose/7.0.1.1)'], 'content-encoding': [''], 'server': ['Jetty(9.2.z-SNAPSHOT)'], 'x-newrelic-app-data': ['PxQEWVNQCwATUFVRDwEOVkYdFGQHBDcQUQxLA1tMXV1dORYnWA1HBxZqGDkLDwp5QwsPJF5dQwMWExoDTFZPUh5SCVYKDgcDBF0VTABNEVddUA5RBwEKCgRVWFAPAwBEOQ=='], 'date': ['Wed, 15 Jul 2015 21:23:44 GMT', 'Wed, 15 Jul 2015 21:23:43 GMT'], 'content-type': ['application/xml;charset=ISO-8859-1']})
```

This is the message "Deleting <server_id>".

**Comment by cyli** [comment]
Ok, looking at all the logs, the logs look like:

1. POST the deleting server request to cloud feeds.  cloud feeds returns a 201.
1. POST the deleting server request to cloud feeds.  cloud feeds returns a 409 - same event id.
1. POST the deleting server request to cloud feeds.  cloud feeds returns a 409 - same event id.
1. POST the deleting server request to cloud feeds.  cloud feeds returns a 409 - same event id.
1. POST the deleting server request to cloud feeds.  cloud feeds returns a 409 - same event id.
1. POST the deleting server request to cloud feeds.  cloud feeds returns a 409 - same event id.
1. Traceback about failing to post the event

It seems like it's retrying 5 times even though the post was successful?

**Comment by cyli** [comment]
Thanks to @radix and @manishtomar for helping me debug this - cloud feeds returns data back in XML format, so even though we got a 201, `service_request` failed because it could not load the body as JSON.

We pass `accept: application/json`, but cloud feeds only returns JSON if we pass `accept: application/vnd.rackspace.atom+json`.
