### ISSUE TITLE
klein dependency can't be upgraded because we use private API

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#889]
Specifically, because we use `klein.test_resource`. Test failures:

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/trial/runner.py", line 498, in loadPackage
    module = modinfo.load()
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/test_webhooks.py", line 20, in <module>
    from otter.test.rest.request import DummyException, RestAPITestMixin
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/request.py", line 9, in <module>
    from klein.test_resource import requestMock
exceptions.ImportError: No module named test_resource

otter.test.rest.test_webhooks
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/trial/runner.py", line 498, in loadPackage
    module = modinfo.load()
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/test_history.py", line 12, in <module>
    from otter.test.rest.request import RestAPITestMixin, request
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/request.py", line 9, in <module>
    from klein.test_resource import requestMock
exceptions.ImportError: No module named test_resource

otter.test.rest.test_history
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/trial/runner.py", line 498, in loadPackage
    module = modinfo.load()
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/test_limits.py", line 9, in <module>
    from otter.test.rest.request import RestAPITestMixin, request
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/request.py", line 9, in <module>
    from klein.test_resource import requestMock
exceptions.ImportError: No module named test_resource

otter.test.rest.test_limits
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/trial/runner.py", line 498, in loadPackage
    module = modinfo.load()
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/test_admin.py", line 9, in <module>
    from otter.test.rest.request import AdminRestAPITestMixin
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/request.py", line 9, in <module>
    from klein.test_resource import requestMock
exceptions.ImportError: No module named test_resource

otter.test.rest.test_admin
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/trial/runner.py", line 498, in loadPackage
    module = modinfo.load()
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/test_policies.py", line 22, in <module>
    from otter.test.rest.request import DummyException, RestAPITestMixin
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/request.py", line 9, in <module>
    from klein.test_resource import requestMock
exceptions.ImportError: No module named test_resource

otter.test.rest.test_policies
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/trial/runner.py", line 498, in loadPackage
    module = modinfo.load()
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/test_groups.py", line 31, in <module>
    from otter.test.rest.request import DummyException, RestAPITestMixin
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/request.py", line 9, in <module>
    from klein.test_resource import requestMock
exceptions.ImportError: No module named test_resource

otter.test.rest.test_groups
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/trial/runner.py", line 498, in loadPackage
    module = modinfo.load()
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/test_configs.py", line 24, in <module>
    from otter.test.rest.request import DummyException, RestAPITestMixin
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/request.py", line 9, in <module>
    from klein.test_resource import requestMock
exceptions.ImportError: No module named test_resource

otter.test.rest.test_configs
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/trial/runner.py", line 498, in loadPackage
    module = modinfo.load()
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/test_application.py", line 15, in <module>
    from otter.test.rest.request import RequestTestMixin, RestAPITestMixin
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/request.py", line 9, in <module>
    from klein.test_resource import requestMock
exceptions.ImportError: No module named test_resource

otter.test.rest.test_application
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/trial/runner.py", line 498, in loadPackage
    module = modinfo.load()
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/test_metrics.py", line 10, in <module>
    from otter.test.rest.request import AdminRestAPITestMixin
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/request.py", line 9, in <module>
    from klein.test_resource import requestMock
exceptions.ImportError: No module named test_resource
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/trial/runner.py", line 498, in loadPackage
    module = modinfo.load()
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/python/reflect.py", line 250, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/Users/lvh/Code/rackspace/otter/otter/test/unitgration/test_rest_cass_model.py", line 30, in <module>
    from otter.test.rest.request import path_only, request, RequestTestMixin
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/request.py", line 9, in <module>
    from klein.test_resource import requestMock
exceptions.ImportError: No module named test_resource

otter.test.unitgration.test_rest_cass_model
-------------------------------------------------------------------------------
```

**Comment by lvh** [comment]
Fortunately, this one is really easy to fix, because all that really happened is that a test package got introduced. Therefore, I'm going to do it as part of #877.

**Comment by lvh** [comment]
So, klein doesn't install its test package. I think that's a bug, but I'm not sure.

**Comment by lvh** [comment]
Okay, crap, it's worse than I thought. It's *not* just the introduction of an API, and the tests *hella* fail when this gets upgraded.

I'm going to close this in favor of a new ticket that's actually about upgrading klein, whatever that may be.

**Comment by lvh** [comment]
It seems to be the same failure tons of times, so I'm hopeful maybe I can fix it:

```
[FAIL]
Traceback (most recent call last):
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/request.py", line 310, in test_invalid_methods_are_405
    self.assert_status_code(405, method=method)
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/request.py", line 239, in assert_status_code
    response_wrapper = self.request(endpoint, method, body, root)
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/request.py", line 270, in request
    request(root, method, endpoint or self.endpoint, body=body))
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 623, in successResultOf
    deferred, result[0].getTraceback()))
twisted.trial.unittest.FailTest: Success result expected on <Deferred at 0x106996ea8 current result: None>, found failure result instead:
Traceback (most recent call last):
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/request.py", line 270, in request
    request(root, method, endpoint or self.endpoint, body=body))
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/request.py", line 126, in request
    mock_request).addCallback(build_response)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallback
    callbackKeywords=kw)
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/internet/defer.py", line 295, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/Users/lvh/.pyenv/versions/otter/lib/python2.7/site-packages/twisted/internet/defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/lvh/Code/rackspace/otter/otter/test/rest/request.py", line 120, in build_response
    [call[1][0] for call in mock_request.write.mock_calls])
exceptions.AttributeError: 'function' object has no attribute 'mock_calls'


otter.test.rest.test_policies.AllPoliciesTestCase.test_invalid_methods_are_405
```
